---
title: "p8105_hw5_sl4269"
author: "Steven Lawrence"
date: "November 4, 2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)

set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))


```
#Problem 1

```{r}

df<-tibble(
num_vec <- c(1,2,3,NA,5),
cha_vec <- c("a","b",NA,"d","c"))
class(df$`cha_vec <- c("a", "b", NA, "d", "c")`)

rep_miss<- function(x){
  
  if(class(x) == "numeric"){
    new_x = replace_na(x, mean(x, na.rm = T))
  
  } else{
    new_x = replace_na(x,"virginica")
  }
  
  new_x
  
}
output = map( df, rep_miss )

output

rep_miss(df$`cha_vec <- c("a", "b", NA, "d", "c")`)


```

```{r}
iris_with_missing %>% map(rep_miss)


```

#Problem 2

```{r}
list.files("./data/")
```


#Problem 3

```{r}

sim_fun <- function(n = 30, beta1 , beta0 = 2, sig2 = 50){

  sim_data <- tibble(
                x = rnorm(n ,0,1),
                e = rnorm(n, 0, sig2),
                y = beta0 + beta1*x + e
              )

  linreg<-lm(y ~ x, data = sim_data)

  
  
  return(tibble(
  b1h = linreg$coefficients[2],
  pval= summary(linreg)$coefficients[8]
  ))
  
}

beta1_value_p <- data.frame()

beta1_value_p <- rbind(sim_fun(beta1 = 0), beta1_value_p)

beta1_value_p

beta1_value_p <- rbind(sim_fun(beta1 = 0), beta1_value_p)

beta1_value_p <- rbind(sim_fun(beta1 = 0), beta1_value_p)

beta1_value_p <- rbind(sim_fun(beta1 = 0), beta1_value_p)

beta1_value_p <- rbind(sim_fun(beta1 = 0), beta1_value_p)

 1:10 %>% map(sim_fun, beta1 = 0) %>% map_dfr(rbind) 

```



